/**
 * @fileoverview QRCode SVG component
 * @description Drop-in React component for rendering QR codes as SVG.
 * @module @qr-plus/react/QRCode
 */

"use client";

import type { QRCodeProps } from "./types";
import { useQRCode } from "./useQRCode";

/**
 * Renders a QR code as an inline SVG element.
 *
 * This is the primary component — SVG-first, scalable, SSR-compatible markup,
 * and supports all module shapes (square, rounded, circle, dot).
 *
 * @example Basic usage
 * ```tsx
 * <QRCode value="https://example.com" />
 * ```
 *
 * @example Custom styling
 * ```tsx
 * <QRCode
 *   value="https://example.com"
 *   size={240}
 *   errorCorrectionLevel="H"
 *   moduleShape="rounded"
 *   cornerRadius={0.3}
 *   darkColor="#111827"
 *   lightColor="#ffffff"
 *   className="shadow-lg rounded-lg"
 * />
 * ```
 */
function QRCode({
  value,
  size,
  margin,
  errorCorrectionLevel,
  darkColor,
  lightColor,
  moduleShape,
  cornerRadius,
  className,
  title,
}: QRCodeProps) {
  const { svgString, isError } = useQRCode(value, {
    size,
    margin,
    errorCorrectionLevel,
    darkColor,
    lightColor,
    moduleShape,
    cornerRadius,
  });

  if (isError || !svgString) {
    return null;
  }

  return (
    <div
      className={className}
      role="img"
      aria-label={title ?? "QR Code"}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG generated by @qr-plus/core, not user input
      dangerouslySetInnerHTML={{ __html: svgString }}
    />
  );
}

export { QRCode };
